/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package jarkz.lab8;

import java.io.IOException;

import jarkz.lab8.core.Parser;
import jarkz.lab8.core.Worker;
import jarkz.lab8.document.Text;

public class App {

	public static void main(String[] args) {
		String resourceName = "data.txt";
		try {
			Parser parser = new Parser(resourceName);
			Text text = parser.parseResource();
			Worker worker = new Worker(text);
			worker.printWordsWithSize(5);
		} catch (IOException e) {
			e.printStackTrace();
		}
	}
}
