package jarkz.lab4.utils;

import jarkz.lab4.builders.CommonStateBuilder;
import jarkz.lab4.entities.State;
import jarkz.lab4.types.LocalityType;

public class Preparer {

    public static State prepareBelarussianState(){
        var builder = CommonStateBuilder.newDescendingBuilder();
        builder
            .newState()
                .newRegion()
                    .newDistrict()
                        .newLocality("Minsk", LocalityType.CAPITAL, 1_996_553L)
                        .newLocality("Zaslauje", LocalityType.CITY, 17_701L)
                        .newLocality("Baravlyany", LocalityType.VILLAGE, 19_210L)
                        .newLocality("Drozdovo", LocalityType.VILLAGE, 515L)
                    .groupToDistrict("Minskij", 1_903L)
                    .newDistrict()
                        .newLocality("Berazino", LocalityType.DISTRICT_CENTER, 11_450L)
                        .newLocality("Aĺchoŭka", LocalityType.VILLAGE, 47L)
                        .newLocality("Bahuševičy", LocalityType.AGRICULTURAL_TOWN, 386L)
                        .newLocality("Mancha", LocalityType.VILLAGE, 60L)
                    .groupToDistrict("Byarezinsky", 1_940L)
                    .newDistrict()
                        .newLocality("Barysaŭ", LocalityType.DISTRICT_CENTER, 140_700L)
                        .newLocality("Biarozaŭka", LocalityType.VILLAGE, 7L)
                        .newLocality("Zabraddze", LocalityType.VILLAGE, 41L)
                    .groupToDistrict("Barysaŭski", 2_987L)
                    .newDistrict()
                        .newLocality("Vileyka", LocalityType.DISTRICT_CENTER, 27_161L)
                        .newLocality("Kuchki", LocalityType.VILLAGE, 10L)
                        .newLocality("Viazyń", LocalityType.AGRICULTURAL_TOWN, 557L)
                        .newLocality("Bubny", LocalityType.VILLAGE, 182L)
                        .newLocality("Dolginovo", LocalityType.AGRICULTURAL_TOWN, 1165L)
                    .groupToDistrict("Viliejski", 2454L)
                    .newDistrict()
                        .newLocality("Miadzieĺ", LocalityType.DISTRICT_CENTER, 6871L)
                        .newLocality("Kryvičy", LocalityType.SETTLEMENT, 1232L)
                        .newLocality("Svir", LocalityType.SETTLEMENT, 909L)
                    .groupToDistrict("Miadzieĺski", 1_964L)
                .groupToRegion("Minskaya")
                .newRegion()
                    .newDistrict()
                        .newLocality("Brest", LocalityType.REGIONAL_CENTER, 340_318L)
                        .newLocality("Damačava", LocalityType.SETTLEMENT, 1224L)
                        .newLocality("Znamenka", LocalityType.AGRICULTURAL_TOWN, 1487L)
                        .newLocality("Kliejniki", LocalityType.AGRICULTURAL_TOWN, 2003L)
                    .groupToDistrict("Brestskij", 1534L)
                    .newDistrict()
                        .newLocality("Baranavičy", LocalityType.DISTRICT_CENTER, 174_183L)
                        .newLocality("Rusino", LocalityType.AGRICULTURAL_TOWN, 1662L)
                        .newLocality("Voĺna", LocalityType.AGRICULTURAL_TOWN, 539L)
                        .newLocality("Haradzišča", LocalityType.SETTLEMENT, 1873L)
                    .groupToDistrict("Baranavicki", 2170L)
                    .newDistrict()
                        .newLocality("Biaroza", LocalityType.DISTRICT_CENTER, 28_619L)
                        .newLocality("Ździtava", LocalityType.AGRICULTURAL_TOWN, 480L)
                        .newLocality("Malech", LocalityType.AGRICULTURAL_TOWN, 1491L)
                        .newLocality("Mižliessie", LocalityType.AGRICULTURAL_TOWN, 507L)
                    .groupToDistrict("Biarozaŭski", 1406L)
                    .newDistrict()
                        .newLocality("Hancavičy", LocalityType.DISTRICT_CENTER, 13_777L)
                        .newLocality("Dzianiskavičy", LocalityType.VILLAGE, 778L)
                        .newLocality("Lyubashava", LocalityType.VILLAGE, 864L)
                        .newLocality("Lyusino", LocalityType.AGRICULTURAL_TOWN, 1117L)
                    .groupToDistrict("Hancavicki", 1_709L)
                    .newDistrict()
                        .newLocality("Drahičyn", LocalityType.DISTRICT_CENTER, 14_855L)
                        .newLocality("Antopaĺ", LocalityType.SETTLEMENT, 1532L)
                        .newLocality("Biezdziež", LocalityType.AGRICULTURAL_TOWN, 861L)
                        .newLocality("Braševičy", LocalityType.AGRICULTURAL_TOWN, 696L)
                    .groupToDistrict("Drahičynski", 1_855L)
                .groupToRegion("Brestskaya")
                .newRegion()
                    .newDistrict()
                        .newLocality("Viciebsk", LocalityType.REGIONAL_CENTER, 1_103_833L)
                        .newLocality("Bábiničy", LocalityType.AGRICULTURAL_TOWN, 1267L)
                        .newLocality("Nóŭka", LocalityType.AGRICULTURAL_TOWN, 3499L)
                        .newLocality("Biešankóvičy", LocalityType.SETTLEMENT, 6701L)
                    .groupToDistrict("Viciebski", 2737)
                    .newDistrict()
                        .newLocality("Polatsk", LocalityType.DISTRICT_CENTER, 79_896L)
                        .newLocality("Babyničy", LocalityType.VILLAGE, 174L)
                        .newLocality("Malóe Sítna", LocalityType.VILLAGE, 233L)
                        .newLocality("Hómieĺ", LocalityType.AGRICULTURAL_TOWN, 282L)
                    .groupToDistrict("Polacki", 3169L)
                    .newDistrict()
                        .newLocality("Braslaŭ", LocalityType.DISTRICT_CENTER, 9829L)
                        .newLocality("Achremaŭcy", LocalityType.AGRICULTURAL_TOWN, 1209L)
                        .newLocality("Vidzy", LocalityType.SETTLEMENT, 1506L)
                        .newLocality("Druja", LocalityType.AGRICULTURAL_TOWN, 865L)
                    .groupToDistrict("Braslaŭski", 2_270L)
                    .newDistrict()
                        .newLocality("Orša", LocalityType.DISTRICT_CENTER, 108_100L)
                        .newLocality("Andrejeŭščyna", LocalityType.VILLAGE, 1121L)
                        .newLocality("Babiniči", LocalityType.AGRICULTURAL_TOWN, 3985L)
                        .newLocality("Smaĺjany", LocalityType.AGRICULTURAL_TOWN, 1163L)
                    .groupToDistrict("Aršanski", 1707L)
                    .newDistrict()
                        .newLocality("Halubičy", LocalityType.DISTRICT_CENTER, 325L)
                        .newLocality("Ziabki", LocalityType.VILLAGE, 159L)
                        .newLocality("Aziarcy", LocalityType.AGRICULTURAL_TOWN, 556L)
                        .newLocality("Plissa", LocalityType.VILLAGE, 367L)
                    .groupToDistrict("Hlybocki", 1_760L)
                .groupToRegion("Vitebskaya")
                .newRegion()
                    .newDistrict()
                        .newLocality("Hrodna", LocalityType.REGIONAL_CENTER, 357_493L)
                        .newLocality("Vierciališki", LocalityType.AGRICULTURAL_TOWN, 3250L)
                        .newLocality("Hoža", LocalityType.AGRICULTURAL_TOWN, 905L)
                        .newLocality("Indura", LocalityType.AGRICULTURAL_TOWN, 1360L)
                    .groupToDistrict("Hrodzienski", 2_594L)
                    .newDistrict()
                        .newLocality("Vialikaja Bierastavica", LocalityType.DISTRICT_CENTER, 5545L)
                        .newLocality("Bierastavičany", LocalityType.VILLAGE, 55L)
                        .newLocality("Kaniuchi", LocalityType.AGRICULTURAL_TOWN, 321L)
                        .newLocality("Malaja Bierastavica", LocalityType.AGRICULTURAL_TOWN, 1174L)
                    .groupToDistrict("Bierastavicki", 744L)
                    .newDistrict()
                        .newLocality("Vaŭkavysk", LocalityType.DISTRICT_CENTER, 67_173L)
                        .newLocality("Viarejki", LocalityType.AGRICULTURAL_TOWN, 984L)
                        .newLocality("Voŭpa", LocalityType.AGRICULTURAL_TOWN, 721L)
                        .newLocality("Gnezna", LocalityType.AGRICULTURAL_TOWN, 523L)
                    .groupToDistrict("Vaŭkavyski", 1_192L)
                    .newDistrict()
                        .newLocality("Dziátlava", LocalityType.DISTRICT_CENTER, 7624L)
                        .newLocality("Venzavets", LocalityType.AGRICULTURAL_TOWN, 646L)
                        .newLocality("Dvarec", LocalityType.AGRICULTURAL_TOWN, 810L)
                        .newLocality("Казлоўшчына", LocalityType.SETTLEMENT, 1673L)
                    .groupToDistrict("Dziatlaŭski", 1_544L)
                    .newDistrict()
                        .newLocality("Voranava", LocalityType.DISTRICT_CENTER, 6434L)
                        .newLocality("Bastuny", LocalityType.VILLAGE, 638L)
                        .newLocality("Bieniakoni", LocalityType.AGRICULTURAL_TOWN, 1319L)
                        .newLocality("Hirki", LocalityType.AGRICULTURAL_TOWN, 149L)
                    .groupToDistrict("Voranaŭski", 1_418L)
                .groupToRegion("Hrodzienskaja")
                .newRegion()
                    .newDistrict()
                        .newLocality("Homieĺ", LocalityType.REGIONAL_CENTER, 503_984L)
                        .newLocality("Azdzielina", LocalityType.AGRICULTURAL_TOWN, 486L)
                        .newLocality("Hrabaŭka", LocalityType.VILLAGE, 824L)
                        .newLocality("Markavičy", LocalityType.VILLAGE, 887L)
                    .groupToDistrict("Homieĺski", 1_951L)
                    .newDistrict()
                        .newLocality("Vietka", LocalityType.DISTRICT_CENTER, 8505L)
                        .newLocality("Vialikija Niamki", LocalityType.AGRICULTURAL_TOWN, 520L)
                        .newLocality("Danilavičy", LocalityType.AGRICULTURAL_TOWN, 386L)
                        .newLocality("Nehlyubka", LocalityType.AGRICULTURAL_TOWN, 828L)
                    .groupToDistrict("Vietkaŭski", 1_558L)
                    .newDistrict()
                        .newLocality("Jeĺsk", LocalityType.DISTRICT_CENTER, 9088L)
                        .newLocality("Valaŭsk", LocalityType.AGRICULTURAL_TOWN, 786L)
                        .newLocality("Dabryń", LocalityType.AGRICULTURAL_TOWN, 688L)
                        .newLocality("Zasincy", LocalityType.AGRICULTURAL_TOWN, 322L)
                    .groupToDistrict("Jeĺski", 1_366L)
                    .newDistrict()
                        .newLocality("Mazýr", LocalityType.DISTRICT_CENTER, 104_967L)
                        .newLocality("Barbaróŭ", LocalityType.AGRICULTURAL_TOWN, 244L)
                        .newLocality("Kamienka", LocalityType.AGRICULTURAL_TOWN, 684L)
                        .newLocality("Kozienki", LocalityType.AGRICULTURAL_TOWN, 3862L)
                    .groupToDistrict("Mazyrski", 1_604L)
                    .newDistrict()
                        .newLocality("Svietlahorsk", LocalityType.DISTRICT_CENTER, 64_989L)
                        .newLocality("Baraviki", LocalityType.AGRICULTURAL_TOWN, 764L)
                        .newLocality("Zahorje", LocalityType.AGRICULTURAL_TOWN, 290L)
                        .newLocality("Krasnoŭka", LocalityType.VILLAGE, 128L)
                    .groupToDistrict("Svietlahorski", 1_900L)
                .groupToRegion("Homieĺskaja")
                .newRegion()
                    .newDistrict()
                        .newLocality("Mahilioŭ", LocalityType.REGIONAL_CENTER, 355_436L)
                        .newLocality("Bujničy", LocalityType.AGRICULTURAL_TOWN, 1_538L)
                        .newLocality("Vyendaraj", LocalityType.AGRICULTURAL_TOWN, 325L)
                        .newLocality("Padgorje", LocalityType.VILLAGE, 521L)
                    .groupToDistrict("Mahilioŭski", 1895L)
                    .newDistrict()
                        .newLocality("Hórki", LocalityType.DISTRICT_CENTER, 30_500L)
                        .newLocality("Lénina", LocalityType.AGRICULTURAL_TOWN, 1481L)
                        .newLocality("Hory", LocalityType.AGRICULTURAL_TOWN, 640L)
                        .newLocality("Dobraja", LocalityType.AGRICULTURAL_TOWN, 406L)
                    .groupToDistrict("Horacki", 1_284L)
                    .newDistrict()
                        .newLocality("Babrujsk", LocalityType.DISTRICT_CENTER, 209_675L)
                        .newLocality("Vialikija Bórtniki", LocalityType.AGRICULTURAL_TOWN, 827L)
                        .newLocality("Višnioŭka", LocalityType.VILLAGE, 358L)
                        .newLocality("Slabodka", LocalityType.VILLAGE, 427L)
                    .groupToDistrict("Babrujski", 1_599L)
                    .newDistrict()
                        .newLocality("Kryčaŭ", LocalityType.DISTRICT_CENTER, 24_500L)
                        .newLocality("Bacvinaŭka", LocalityType.AGRICULTURAL_TOWN, 372L)
                        .newLocality("Kasciuškavičy", LocalityType.AGRICULTURAL_TOWN, 395L)
                        .newLocality("Bieĺ-1", LocalityType.AGRICULTURAL_TOWN, 385L)
                    .groupToDistrict("Kryčaŭski", 778L)
                    .newDistrict()
                        .newLocality("Škloŭ", LocalityType.DISTRICT_CENTER, 15_400L)
                        .newLocality("Faščaŭka", LocalityType.AGRICULTURAL_TOWN, 547L)
                        .newLocality("Haviády", LocalityType.AGRICULTURAL_TOWN, 593L)
                        .newLocality("Haradzišča", LocalityType.AGRICULTURAL_TOWN, 625L)
                    .groupToDistrict("Škloŭski", 1_334L)
                .groupToRegion("Mahilioŭskaja")
            .groupToState("Belarus");
        return builder.build();
    }
}
