/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package jarkz.lab8;

import org.junit.Test;
import org.junit.Assert;

import jarkz.lab8.document.Sentence;

public class AppTest {
	@Test
	public void testSentence() {
		String testText = "\"Rural juror\" is a difficult :'phrase due to its' alliteration and the fact that the combination of \"rural\" and \"juror\" is not commonly used in everyday language.";
		Sentence sentence = new Sentence(testText);
		Assert.assertEquals(testText, sentence.getString());
	}
}
