/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package jarkz.lab7;

import java.util.logging.Logger;

public class App {

	@FunctionalInterface
	private interface Predicate {
		boolean apply(int function);
	}

    public static void main(String[] args) {
		Predicate function = (number -> number % 31 == 0);

		int validNumber = 726_113;
		int invalidNumber = 234_324;

		Logger logger = Logger.getLogger("LOGGER");
		logger.info("Validation of valid number " + validNumber + "\nResult: " + function.apply(validNumber));
		logger.info("Validation of invalid number " + invalidNumber + "\nResult: " + function.apply(invalidNumber));
    }
}
