/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package jarkz.lab2;

import jarkz.lab2.utils.Computator;
import jarkz.lab2.utils.Generator;

public class App {

    public static void main(String[] args) {
		var integerMatrix = Generator.generateMatrix(6, 20);
		System.out.println(integerMatrix.toString());
		// integerMatrix.toTransport();
		// System.out.println(integerMatrix.toString());
		int sum = Computator.computeIntegerSumBetweenFirstTwoPositiveNumbers(integerMatrix);
		System.out.println(sum);
    }
}
