/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package jarkz.lab1;

import java.util.Arrays;
import java.util.logging.Logger;
import java.util.stream.IntStream;

public class App {
    public static void main(String[] args) {
		Logger logger = Logger.getGlobal();
		int count = -1;
		try {
			count = Integer.parseInt(args[0]);
		} catch (NumberFormatException e){
			logger.warning("Invalid number as argument!");
			System.exit(1);
		} catch (ArrayIndexOutOfBoundsException e){
			logger.warning("Not received argument!");
			System.exit(1);
		}
		int[] numbers = IntStream.range(1, Integer.MAX_VALUE)
			.parallel()
			.filter(n -> (n % 5 == 0) && (n % 7 == 0))
			.limit(count)
			.toArray();
		System.out.println(Arrays.toString(numbers));
    }
}
